version: '3.4'

services:
  app:
    build: .
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo:27017/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
